### ISSUE TITLE
not setting file owner

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#21] opened 2021-03-01 15:16 UTC
### Description
the file owner is not being set when the rip is complete.

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

```
tawhite@arm:/opt/arm$ git branch
* v2.5.0_dev
tawhite@arm:/opt/arm$ git log -1
commit 608c2ae7160dd0869ae78623e475ff2a0c904324 (HEAD -> v2.5.0_dev, origin/v2.5.0_dev, origin/HEAD)
Author: 1337-server <62730074+1337-server@users.noreply.github.com>
Date:   Mon Feb 15 00:24:37 2021 +0000

    Update greetings.yml
```
it is not fully accurate. i have made some changes (see my PRs) but they are all for the web ui.

### Log file
[TALE_OF_TWO_CITIES_161458190889.log](https://github.com/1337-server/automatic-ripping-machine/files/6062564/TALE_OF_TWO_CITIES_161458190889.log)

**Comment by 1337-server** [comment] 2021-03-02 01:58
```
[01-03-2021 14:59:06] ERROR ARM: main.<module> A fatal error has occurred and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 556, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 185, in main
    db.session.refresh(job)
```

This is a database lockup caused by the manual wait. I will need to change the manual wait to use the database updater function.

**Comment by TomW1605** [comment] 2021-03-02 03:06
[EXCALIBUR.log](https://github.com/1337-server/automatic-ripping-machine/files/6065947/EXCALIBUR.log)

sorry apparently i posted the wrong log. that was for a different issue that happens when i start a bunch of jobs at the same time and i assume that is because one is locking the DB so the others cant edit it.

this log is for a successful job that did not get the owner changed and it defaulted to root. it did change the group and permissions just not the owner

**Comment by 1337-server** [comment] 2021-03-02 03:30
ARM isnt coded to set the owner, confusingly it has config and variables for this. But unfortunatly the code for it was never finished.

Currently only `CHMOD_VALUE` and the  `SET_MEDIA_PERMISSIONS` are ever used used

**Comment by TomW1605** [comment] 2021-03-02 03:38
well that would explain it then. i will see if i can finish that code

**Comment by 1337-server** [comment] 2021-03-11 03:58
I looked into this and it appears that this was intentionally left out, changing owners would require root permission. ARM-ripper runs as user 'arm' so chown wouldn't work. I have added this functionality to the ARMui but its not perfect and it wont work in all cases.

**Comment by TomW1605** [comment] 2021-03-12 01:55
ok that makes sense. if it is not implementable then it might be a good idea to remove the configuration

**Comment by 1337-server** [comment] 2021-03-12 17:20
The latest commit has a new button on the ARMui that used to config vars to set the file permission of the so I'm not sure about removing them.

**Comment by 1337-server** [comment] 2021-04-10 04:12
Closing as ARM now has a button to fix permissions.

**Closed by 1337-server** 2021-04-10 04:12 UTC
Labels: Not a bug
