### ISSUE TITLE
Error "attempt to write a readonly database" deleting job from db

### ISSUE THREAD

**Issue by gingerbeardman** [1337-server/automatic-ripping-machine#147] opened 2022-04-03 14:23 UTC
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
Error when attempting to delete a failed job from database

**To Reproduce**
1. try to delete a job from database

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")] Linux 3.10.105 #25426 SMP Mon Dec 14 18:47:46 CST 2020 x86_64 GNU/Linux synology_broadwell_3617xs
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] docker

### Log
[arm.csv](https://github.com/1337-server/automatic-ripping-machine/files/8404714/arm.csv)

```
2022-04-03 14:24:57,stderr,172.17.0.1 - - [03/Apr/2022 14:24:57] "GET /json?job=1&mode=delete HTTP/1.1" 200 -

2022-04-03 14:24:57,stderr,(Background on this error at: https://sqlalche.me/e/14/e3q8)

2022-04-03 14:24:57,stderr,"[parameters: ('1',)]
"
2022-04-03 14:24:57,stderr,[SQL: DELETE FROM track WHERE track.job_id = ?]

2022-04-03 14:24:57,stderr,"[2022-04-03 14:24:57,545] ERROR in utils: Error:db-1 (sqlite3.OperationalError) attempt to write a readonly database
"
2022-04-03 14:24:57,stderr,"[2022-04-03 14:24:57,542] DEBUG in utils: No errors: job_id=1
"
2022-04-03 14:24:57,stderr,"[2022-04-03 14:24:57,542] DEBUG in utils: Admin requesting delete job 1 from database!
"
2022-04-03 14:24:57,stderr,"[2022-04-03 14:24:57,542] DEBUG in utils: job_id= 1
"
```

### Screenshot
<img width="1080" alt="Screen shot 2022-04-03 at 15 17 19" src="https://user-images.githubusercontent.com/49612/161432566-3b2ae5a9-3873-45db-810e-c5d08beac1e3.png">

**Comment by 1337-server** [comment] 2022-04-03 14:39
Your database file is read only by the arm user. 

This is most likely caused by installer being run as root and creating the database. 
You can check this with `ls -l /path/to/arm/db ` it will most likely be owned by root.
If that's the case, you will need to chmod or chown the database file/folder. Depending on your preference.

The default location is `/home/arm/db/arm.db`

**Comment by gingerbeardman** [comment] 2022-04-03 16:38
But...what installer? I'm using the docker image.

```
-rw-r--r-- 1 1024 users 36864 Apr  3 13:46 /home/arm/db/arm.db                                     
```

**Comment by 1337-server** [comment] 2022-04-04 05:51
Did you visit /setup after running the docker ? /setup creates the db file and then asks you to create an admin account.

The file should be owned by the arm user, can you check that user arm has the ID `1024`

**Comment by 1337-server** [comment] 2022-04-06 16:11
I'll keep this open until I update the service file and install script to be run as arm user by default.

**Comment by gingerbeardman** [comment] 2022-04-06 18:25
I assumed that 1024 and arm were the same, apologies.

**Comment by 1337-server** [comment] 2022-04-08 06:25
No worries.

It should now be fixed, some wiki entries weren't updated. So ill close this.

**Comment by gingerbeardman** [comment] 2022-04-08 10:01
Am I best to delete and reinstall?

**Comment by 1337-server** [comment] 2022-04-08 11:28
You would be fine to just edit the service file `/etc/systemd/system/armui.service`

and add 
```
User=arm
Group=arm
```

after this line 

```
[Service]
Type=simple
```
Delete the db file from inside `/home/arm/db/`

Then you need to reload the service files
```
sudo systemctl daemon-reload
sudo systemctl enable armui
sudo systemctl start armui
```

Now you can visit `/setup` in the UI to create a fresh install, this would save removing everything and then repeating steps. But it's up to you.

**Comment by gingerbeardman** [comment] 2022-04-08 19:35
Hmm.

`cat: /etc/systemd/system/armui.service: No such file or directory`

I think I'll just start again?

**Comment by gingerbeardman** [comment] 2022-04-08 19:39
I notice that the docker image on the hub was last updated 21 days ago? 
https://registry.hub.docker.com/r/1337server/automatic-ripping-machine/

Do I need to install from a newer one?

**Comment by gingerbeardman** [comment] 2022-04-08 20:08
Reinstalled and confirmed I can now delete from DB. Thanks!

My other problems persist: https://github.com/1337-server/automatic-ripping-machine/discussions/146 so will add more info there

**Comment by 1337-server** [comment] 2022-04-08 21:06
synology have their udev rules `/lib/udev/rules.d` from what ive read so you would need to

**Comment by 1337-server** [comment] 2022-04-10 14:33
Could you try the `1337server/automatic-ripping-machine:dev_build` image

It's not a permanent solution, but if you could try it and see if it solves this issue, that would be great.

You would need to modify your docker run command to use the dev_build tag

```
docker run -d \
   -p "8080:8080" \
   -e UID="1000" -e GID="1000" \
   -v "/home/arm:/home/arm" \
   -v "/home/arm/music:/home/arm/music" \
   -v "/home/arm/config:/home/arm/config" \
   -v "/home/arm/logs:/home/arm/logs" \
   -v "/home/arm/media:/home/arm/media" \
   --device=/dev/sr0:/dev/sr0 \
   --device=/dev/sg1:/dev/sg1 \
   --restart "always" \
   --name "arm-rippers" \
   1337server/automatic-ripping-machine:dev_build
```
You may still need the --privileged flag

**Closed** 2022-06-23 18:56 UTC
Labels: bug, Docker
